### PR TITLE
DEVX-3061 add incoming jwt decode snippet

### PR DESCRIPTION
**Pull request by bencgreenberg**
DEVX-3061 Add Incoming JWT Snippet

This adds a snippet to decode an incoming JWT using the standard Ruby JWT library

### CODE REVIEW

**Review by dragonmantank — CHANGES_REQUESTED** [review]
Ultimately this needs to live on https://github.com/Nexmo/nexmo-developer/blob/main/_documentation/en/concepts/guides/webhooks.md, not as a discreet snippet.

Can we also show where the signature is coming from, and pulling in a secret to help decode it?

**Comment by bencgreenberg** [comment]
> Ultimately this needs to live on https://github.com/Nexmo/nexmo-developer/blob/main/_documentation/en/concepts/guides/webhooks.md, not as a discreet snippet.
> 
> Can we also show where the signature is coming from, and pulling in a secret to help decode it?

This code snippet will be referenced here: https://github.com/Nexmo/nexmo-developer/pull/3562

Is that sufficient, or is there something specific for this snippet that needs to be added?

**Comment by dragonmantank** [comment]
> Is that sufficient, or is there something specific for this snippet that needs to be added?

Ah, didn't see that other PR, so since we're pulling it in nevermind! That will be good enough to reference.

**Comment by bencgreenberg** [comment]
> > Is that sufficient, or is there something specific for this snippet that needs to be added?
> 
> Ah, didn't see that other PR, so since we're pulling it in nevermind! That will be good enough to reference.

No worries, lots of PRs everywhere. :) Are we good to go on this one then? It'll unblock the NDP one after.

**Pull request merged**
